const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  navigationText: '#888',
  navigationBackground: 'transparent',
  navigationSelected: '#ffc004',
  homeNavigationText: 'black',
  homeNavigationSelected: '#9268bb',
  underline: '#eee',
  paginationBackground: 'rgba(0, 0, 0, 0.7)',
  paginationText: 'white',
  todayBookBackground: '#7fbaaf',
  todayBookText: 'white',
  quotation: '#888',
};
